<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-10-27 13:51
=======
# Generated by Django 5.2.7 on 2025-10-25 10:15
>>>>>>> 05dbc2951224f83d191a41d085921f840b97ee11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(help_text='Full problem description, supports Markdown.')),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Normal'), (4, 'Hard'), (5, 'Extreme')], default=3)),
                ('time_limit', models.IntegerField(default=1000, help_text='in milliseconds')),
                ('memory_limit', models.IntegerField(default=256, help_text='in MB')),
<<<<<<< HEAD
=======
                ('is_active', models.BooleanField(default=True)),
>>>>>>> 05dbc2951224f83d191a41d085921f840b97ee11
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_problems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('is_hidden', models.BooleanField(default=True, help_text='Hidden test cases are not shown to the user.')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='problems.problem')),
            ],
        ),
    ]
