# Generated by Django 4.2.15 on 2025-11-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='ignore_trailing_whitespace',
            field=models.BooleanField(default=True, help_text='If true, trims whitespace before comparing outputs.'),
        ),
    ]
