# Generated by Django 4.2.15 on 2025-11-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_rating'),
        ('users', '0002_useractivitylog'),
    ]

    operations = [
    ]
