# Generated by Django 4.2.15 on 2025-11-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20251106_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rank',
            field=models.CharField(default='Bronze', max_length=20),
        ),
    ]
