# Generated by Django 4.2.15 on 2025-11-22 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_editorsession_anticheatlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorsession',
            name='match',
        ),
        migrations.RemoveField(
            model_name='editorsession',
            name='user',
        ),
        migrations.DeleteModel(
            name='AntiCheatLog',
        ),
        migrations.DeleteModel(
            name='EditorSession',
        ),
    ]
